### ISSUE TITLE
Circuit Breaker config names are not the same as in Precipice

### ISSUE THREAD

**Issue by nid90** [tbrooks8/Beehive#2]
Here: https://github.com/tbrooks8/Beehive/blob/master/src/beehive/service.clj#L50
`trailingPeriodMillis`is changed to `time-period-in-millis` and so on.

Also, not all the config is exposed for reading.

-- Akshay and Nid

**Comment by tbrooks8** [comment]
I believe that is is completed.

[fa9edfac7f32f47dcf871af3903f57be7371ea0d](https://github.com/tbrooks8/Beehive/commit/fa9edfac7f32f47dcf871af3903f57be7371ea0d)
